CREATE TABLE `travel_posts` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '帖子ID',
  `user_id` bigint NOT NULL COMMENT '发布用户ID',
  `title` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '帖子标题',
  `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '帖子内容',
  `post_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'normal' COMMENT 'normal/review/ai_video',
  `category` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'travel' COMMENT '帖子分类',
  `audit_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'pending',
  `audit_remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '审核备注',
  `images` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '图片URL或Base64数组(JSON)',
  `tags` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '标签数组(JSON)',
  `visibility` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'public',
  `status` tinyint(1) DEFAULT '1' COMMENT '帖子状态：1-正常，0-删除',
  `view_count` int DEFAULT '0' COMMENT '浏览次数',
  `comment_count` int DEFAULT '0' COMMENT '评论数',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '发布时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `collection_count` int DEFAULT NULL,
  `collect_count` int DEFAULT NULL,
  `source_lang` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'normal' COMMENT '????????ormal-????????review-??????',
  `activity_id` bigint DEFAULT NULL,
  `score` int DEFAULT NULL,
  `is_anonymous` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_post_user` (`user_id`),
  KEY `idx_post_category` (`category`),
  KEY `idx_post_status` (`status`),
  KEY `idx_post_create_time` (`create_time`),
  KEY `idx_post_activity` (`activity_id`),
  KEY `idx_travel_posts_activity_id` (`activity_id`),
  KEY `idx_travel_posts_post_type` (`post_type`),
  KEY `idx_travel_posts_user_type_status` (`user_id`,`post_type`,`status`),
  CONSTRAINT `fk_post_activity` FOREIGN KEY (`activity_id`) REFERENCES `activities` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='发现页帖子';


DROP TABLE IF EXISTS `merchant_profiles`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `merchant_profiles` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL COMMENT 'merchant owner account, users.id',
  `shop_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shop_cover` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shop_intro` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contact_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contact_phone` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contact_email` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `province` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `city` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `district` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `heritage_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `heritage_description` text COLLATE utf8mb4_unicode_ci,
  `proof_images` json DEFAULT NULL,
  `business_status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending' COMMENT 'pending/approved/active/rejected/disabled/closed',
  `latest_application_id` bigint DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `avg_score` double DEFAULT '0',
  `review_count` int DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_merchant_profiles_user` (`user_id`),
  KEY `idx_merchant_profiles_status` (`business_status`),
  KEY `idx_merchant_profiles_shop_name` (`shop_name`),
  CONSTRAINT `fk_merchant_profiles_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=10121 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='canonical merchant profile table';

CREATE TABLE `activities` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `merchant_id` bigint NOT NULL,
  `category_id` int DEFAULT NULL,
  `title` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `subtitle` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cover_image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `images` json DEFAULT NULL,
  `video_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `video_cover_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `content` text COLLATE utf8mb4_unicode_ci,
  `activity_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `heritage_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `start_time` datetime NOT NULL,
  `end_time` datetime NOT NULL,
  `signup_start_time` datetime DEFAULT NULL,
  `signup_end_time` datetime DEFAULT NULL,
  `max_participants` int DEFAULT NULL,
  `current_participants` int DEFAULT '0',
  `price` int DEFAULT '0',
  `original_price` int DEFAULT NULL,
  `location_province` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `location_city` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `location_district` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `location_detail` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'signup',
  `audit_status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'pending',
  `audit_remark` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_recommend` tinyint(1) DEFAULT '0',
  `view_count` int DEFAULT '0',
  `signup_count` int DEFAULT '0',
  `collect_count` int DEFAULT '0',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `merchant_profile_id` bigint DEFAULT NULL COMMENT 'normalized merchant id, merchant_profiles.id',
  `avg_score` double DEFAULT '0',
  `review_count` int DEFAULT '0',
  `vr_model_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'VR模型URL',
  PRIMARY KEY (`id`),
  KEY `fk_activities_merchant` (`merchant_id`),
  KEY `idx_activities_merchant_profile` (`merchant_profile_id`),
  CONSTRAINT `fk_activities_merchant` FOREIGN KEY (`merchant_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_activities_merchant_profile` FOREIGN KEY (`merchant_profile_id`) REFERENCES `merchant_profiles` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=90 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;