CREATE TABLE IF NOT EXISTS `activity_reserves` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `reserve_no` varchar(64) NOT NULL,
  `user_id` bigint NOT NULL,
  `merchant_id` bigint NOT NULL,
  `activity_id` bigint NOT NULL,
  `activity_title` varchar(128) NOT NULL,
  `activity_time` varchar(128) NOT NULL,
  `contact_name` varchar(32) NOT NULL,
  `contact_phone` varchar(20) NOT NULL,
  `participant_num` int NOT NULL,
  `total_amount` int NOT NULL,
  `pay_amount` int NOT NULL,
  `pay_status` tinyint DEFAULT 0,
  `reserve_status` varchar(32) DEFAULT 'registered',
  `remark` varchar(512) DEFAULT NULL,
  `payment_type` varchar(32) DEFAULT NULL,
  `payment_time` datetime DEFAULT NULL,
  `cancel_time` datetime DEFAULT NULL,
  `verify_time` datetime DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_activity_reserves_reserve_no` (`reserve_no`),
  KEY `idx_activity_reserves_user_id` (`user_id`),
  KEY `idx_activity_reserves_merchant_id` (`merchant_id`),
  KEY `idx_activity_reserves_activity_id` (`activity_id`),
  KEY `idx_activity_reserves_status` (`reserve_status`),
  CONSTRAINT `fk_activity_reserves_activity` FOREIGN KEY (`activity_id`) REFERENCES `activities` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_activity_reserves_merchant` FOREIGN KEY (`merchant_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_activity_reserves_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `reserve_status_logs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `reserve_id` bigint NOT NULL,
  `old_status` varchar(32) DEFAULT NULL,
  `new_status` varchar(32) NOT NULL,
  `operator_id` bigint NOT NULL,
  `operator_type` varchar(16) NOT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_reserve_status_logs_reserve_id` (`reserve_id`),
  KEY `idx_reserve_status_logs_operator_id` (`operator_id`),
  CONSTRAINT `fk_reserve_status_logs_operator` FOREIGN KEY (`operator_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_reserve_status_logs_reserve` FOREIGN KEY (`reserve_id`) REFERENCES `activity_reserves` (`id`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `merchant_reviews` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `merchant_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `order_id` bigint DEFAULT NULL,
  `reserve_id` bigint DEFAULT NULL,
  `review_type` varchar(20) NOT NULL DEFAULT 'activity',
  `score` decimal(2,1) NOT NULL,
  `content` varchar(500) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_merchant_reviews_merchant` (`merchant_id`),
  KEY `idx_merchant_reviews_user` (`user_id`),
  KEY `idx_merchant_reviews_reserve` (`reserve_id`),
  CONSTRAINT `fk_merchant_reviews_merchant` FOREIGN KEY (`merchant_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_merchant_reviews_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);
